version: "3.0"

services:
  service:
    env_file:
      - ".docker-compose-env"
    build:
      context: 'service'
      dockerfile: 'Dockerfile'
    command: [ "uvicorn", "service.main:app", "--host", "0.0.0.0", "--port", "8075" ]
    ports:
      - "8075"
    volumes:
      - kernel-data:/data/results

  console:
    env_file:
      - ".docker-compose-env"
    build:
      context: 'service'
      dockerfile: 'Dockerfile'
    command: [ "/bin/sh" ]
    volumes:
      - kernel-data:/data/results

volumes:
  kernel-data:
    driver: local
